apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  这个是指我 mysql 要用的东西
  name: webook-mysql-claim
spec:
#   这个可以随便
  storageClassName: suibian
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
#      1GB
      storage: 1Gi